-- MySQL Script generated by MySQL Workbench
-- Sun Feb 21 23:13:10 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema checkin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema checkin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkin` DEFAULT CHARACTER SET utf16 ;
USE `checkin` ;

-- -----------------------------------------------------
-- Table `checkin`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkin`.`sessions` (
  `username` VARCHAR(50) NOT NULL,
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `session` VARCHAR(45) NULL DEFAULT NULL,
  `creation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_access_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 193
  DEFAULT CHARACTER SET = utf16;


-- -----------------------------------------------------
-- Table `checkin`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkin`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `creation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
